### ISSUE TITLE
OCaml 5 support

### ISSUE THREAD

**Issue by sim642** [ocaml-batteries-team/batteries-included#1081]
Currently the upper bound on ocaml forbids version 5.0:
https://github.com/ocaml-batteries-team/batteries-included/blob/77bd2aace3e16499ec71bf544270e169656c3c23/batteries.opam#L22

Although OCaml 5 isn't yet final, many libraries have been made compatible already. Would be nice if batteries could also do the same.

Maybe it would just be a version bump, maybe it requires more changes. Either way, an issue to track that progress doesn't hurt.

### TODO
- [ ] `ocamlfind: Package bigarray not found` — bigarray is directly inside `Stdlib` since OCaml 4.07, but OCaml 5 removes the package definition (https://github.com/ocaml/ocaml/pull/10896).
- [ ] `Error: Unbound module Pervasives` — OCaml 5 removes the deprecated `Pervasives` in favor of `Stdlib` (https://github.com/ocaml/ocaml/pull/10896).
- [ ] OCaml 5 removes `Stream` and `Genlex` (https://github.com/ocaml/ocaml/pull/10896) so `BatStream` and `BatGenlex` shouldn't be available on OCaml 5 either?

**Comment by UnixJunkie** [comment]
Yeah, doesn't hurt to track our compatibility.

**Comment by UnixJunkie** [comment]
If you can do 'make -k' in your batteries checkout with an OCaml-5 compiler and post the output here, it might tell us how much work is needed.

**Comment by sim642** [comment]
Gave that a shot, after installing all non-ocaml dependencies (which luckily are available on OCaml 5).
First hit the issue about bigarray package not being found, which was easy to work around, but `Pervasives` being removed probably requires a lot more changes (and thinking how to bake it backwards-compatible in batteries). Added these as tasks to the initial issue description.

**Comment by UnixJunkie** [comment]
Can you copy-paste the whole compilation log?
Or link a gist with it?

**Comment by sim642** [comment]
There's not much, out of the box `make -k` outputs:
```
Build mode: shared
ocamlbuild -no-links -use-ocamlfind src/batteries.cma toplevel/batteriesHelp.cmo src/batteriesThread.cma META src/batteries.cmxs src/batteriesThread.cmxs
Finished, 0 targets (0 cached) in 00:00:00.
+ ocamlfind ocamldep -package bigarray,num,str -package bytes -modules src/batOpaqueInnerSys.ml > src/batOpaqueInnerSys.ml.depends
ocamlfind: Package `bigarray' not found
Command exited with code 2.
Compilation unsuccessful after building 272 targets (271 cached) in 00:00:00.
make: *** [Makefile:107: all] Error 10
```

After removing the bigarray package from here
https://github.com/ocaml-batteries-team/batteries-included/blob/77bd2aace3e16499ec71bf544270e169656c3c23/myocamlbuild.ml#L12
it outputs:
```
Build mode: shared
ocamlbuild -no-links -use-ocamlfind src/batteries.cma toplevel/batteriesHelp.cmo src/batteriesThread.cma META src/batteries.cmxs src/batteriesThread.cmxs
Finished, 1 target (0 cached) in 00:00:00.
+ ocamlfind ocamlc -c -g -bin-annot -safe-string -no-alias-deps -strict-sequence -w -3 -package num,str -warn-error -50 -package bytes -I src -I qtest -I benchsuite -I toplevel -I build -I testsuite -I benchsuite/lib -o src/batPervasives.cmi src/batPervasives.mli
File "src/batPervasives.mliv", line 50, characters 18-39:
Error: Unbound module Pervasives
Command exited with code 2.
Compilation unsuccessful after building 88 targets (0 cached) in 00:00:02.
make: *** [Makefile:107: all] Error 10
```

**Comment by UnixJunkie** [comment]
Could you run
```bash
opam install base-bigarray
```
so that the compilation runs further

**Comment by sim642** [comment]
> Could you run
> 
> ```shell
> opam install base-bigarray
> ```
> 
> so that the compilation runs further

I already have that installed, so that doesn't help. I think the base-bigarray package itself contains nothing and just expects it to come from the compiler, where it was changed from a compiler-provided package to being integrated into the standard library without needing to depend on a package.

The separate bigarray-compat package that maybe provides the compatibility, but it has the dependency `"ocaml" {>= "4.02.3"}`, whereas batteries itself goes lower and allows 4.00.0. Probably will be easier to just have the compatibility switching entirely inside batteries.

**Comment by UnixJunkie** [comment]
@gasche are we supposed to start depending on bigarray-compat and rewrite our code concerning bigarrays?

**Comment by sim642** [comment]
I made a brutal attempt for this in #1085.

**Comment by UnixJunkie** [comment]
I think we are good here.

**Comment by sim642** [comment]
The changelog is still missing all the OCaml 5 related changes. Including some potentially breaking ones like the increased lower bound on OCaml and maybe something else I'm forgetting.

**Comment by kit-ty-kate** [comment]
Any news on the release? OCaml 5.0 is to be released next week

**Comment by UnixJunkie** [comment]
I will look into it during this week.

**Comment by UnixJunkie** [comment]
there is at least one unit test error in ocaml-5:
```
Failure: >enum>src/batBuffer.mlv:48

test `src/batBuffer.mlv:48:  (Q.string) (fun s -> let b = create 10 in add_string b s; BatEnum.equal Char.equal (enum b) (BatString.enum s))`
failed on ≥ 1 cases: "a" (after 19 shrink steps)
                       
///////////////////////////////////////////////////////////////////////////////
Ran: 2115 tests in: 22.17 seconds.                                        
FAILURE
```

**Comment by UnixJunkie** [comment]
If I try to do update a build, I also get this funny error with ocaml-5:
```Fatal error: cannot load shared library dllcamlstr
Reason: /home/fbr/.opam/5.0.0~rc1/lib/ocaml/stublibs/dllcamlstr.so: undefined symbol: caml_state
Aborted (core dumped)
Command exited with code 134.
```

**Comment by UnixJunkie** [comment]
I don't understand the problem with BatBuffer.enum and ocaml-5.
I'll see tomorrow if a fresh mind is more helpful.
Don't hesitate if you have any hint.

**Comment by UnixJunkie** [comment]
I can correct the implementation of enum; but I don't really know what is the underlying problem.
Maybe related to strings becoming constants from ocaml-5.

**Comment by UnixJunkie** [comment]
I have issued temporary tag v360_test_01.
If tests are OK in opam-repos., I will issue the proper tag.

**Comment by sim642** [comment]
At one point there was mention of this going into a major release, which would be 4.0.0 I guess:

> I think the next thing so that we can make a new major release is to get rid of the oasis remaining bits.

Will that not be the case?

**Comment by UnixJunkie** [comment]
there is a single "breaking" change in BatRandom.choice; documented in the changelog.
I think it is a little light to justify a major release.
